Repository amadzuki/saikou-client, pull requests merged in 2020-07, with the labels that each got.

#14 Refactor component and delete unused files
  src/App.js
  src/components/ScrollToTop.js
  src/data/oldProducts.json
  src/data/transformer.js
Labels: bug

#23 Convert to JPG and resize width to 120
  public/avatars/chibi-c2.jpg
  public/avatars/chibi-c2.png
  public/avatars/chibi-goku.jpg
  public/avatars/chibi-goku.png
  public/avatars/chibi-hiruma.jpg
  public/avatars/chibi-hiruma.png
  public/avatars/chibi-hitsugaya.jpg
  public/avatars/chibi-hitsugaya.png
  public/avatars/chibi-l.jpg
  public/avatars/chibi-l.png
  public/avatars/chibi-lelouch.jpg
  public/avatars/chibi-lelouch.png
  public/avatars/chibi-luffy.jpg
  public/avatars/chibi-luffy.png
  public/avatars/chibi-meliodas.jpg
  public/avatars/chibi-mikasa.jpg
  public/avatars/chibi-mikasa.png
  public/avatars/chibi-miyamura.jpg
  public/avatars/chibi-miyamura.png
  public/avatars/chibi-nao.jpg
  public/avatars/chibi-nao.png
  public/avatars/chibi-naofumi.jpg
  public/avatars/chibi-naofumi.png
  public/avatars/chibi-naruto.jpg
  public/avatars/chibi-naruto.png
  public/avatars/chibi-saitama.jpg
  public/avatars/chibi-saitama.png
  public/avatars/chibi-sasuke.jpg
  public/avatars/chibi-sasuke.png
  public/avatars/chibi-shiro.jpg
  public/avatars/chibi-shiro.png
  public/avatars/chibi-tanjiro.jpg
  public/avatars/chibi-tanjiro.png
  src/data/users.json
Labels: enhancement

#25 Create debug mode
  .env.schema
  .gitignore
  package.json
  setup.sh
  src/App.js
  src/pages/debug.js
  src/utils/fetch.js
  yarn.lock
Labels: bug, enhancement
